### ISSUE TITLE
Migrating old sites to Gem-based themes

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-jekyll-theme#1]
# Instructions

## 1. Determine any special functionality of this theme

If your theme has any customizations to the `docs/src/_layouts`, `docs/src/_includes` you need to get those files into `docs/_layouts/whatever.html` and `docs/_includes/whatever.html` (basically just drop the individual files down one level in the tree)

Example:
``` sh
' Copy this:
docs/src/_includes/custom_thing.html 
' To here:
docs/_includes/custom_thing.html
```

***NB: Mailchimp sidebar***

The mailchimp code has been moved to an extension file called `docs/_includes/sidebar.html`. Please put only the mailchimp stuff there.

## 2. Create `docs/Gemfile`

``` Gemfile
# frozen_string_literal: true

source "https://rubygems.org"
gem "jekyll-remote-theme" 
```

## 3. Alter `docs/.gitignore`
```txt
Gemfile.lock
```

### Add lines:

``` yaml
exclude:
  - src
  - LICENSE
  - README.md
  - _config.yml
  - Gemfile*   # <----- just this at the end of the excludes

# NOTE: Add these 3 lines near the bottom of the file
# ----------------------------------------------------
remote_theme: Riverscapes/riverscapes-jekyll-theme
plugins:
  - jekyll-remote-theme 
```

### Remove Lines:

```yaml
# Where our layouts and templates are stored
layouts_dir:  src/_layouts
includes_dir: src/_includes
```

## 5. Remove these files:

* `docs/assets/css/app.css`
* `docs/assets/css/app.css.map`

## 6. Remove these folders:

* `docs/assets/fonts/`
* `docs/assets/js/`
* `docs/src/`
* `docs/assets/images/favicons/`

## 7. Commit, push, test
